package com.example.tightbudget.utils

/**
 * Helper class for dashboard-specific functionality
 * This class provides methods to limit the number of categories displayed,
 * get emojis for categories, and format currency amounts.
 *
 * This class was generated by ChatGPT and was edited by me to match the app's needs.
 */
object DashboardHelper {

    /**
     * Limits category data to the top N categories by spending amount
     *
     * @param spendingData Map of category name to spending amount
     * @param limit Maximum number of categories to return (default 4)
     * @return Limited map of categories with their spending amounts
     */
    fun limitTopCategories(spendingData: Map<String, Double>, limit: Int = 4): Map<String, Double> {
        if (spendingData.size <= limit) {
            return spendingData
        }

        // Sort categories by spending amount (descending) and take top N
        return spendingData.entries
            .sortedByDescending { it.value }
            .take(limit)
            .associate { it.key to it.value }
    }

    /**
     * Retrieves the appropriate emoji icon for a category name.
     * This method delegates directly to IconProvider for centralised icon management.
     *
     * @param categoryName Name of the category
     * @return Emoji corresponding to the category
     */
    fun getCategoryEmoji(categoryName: String): String {
        return IconProvider.getCategoryIcon(categoryName)
    }

    /**
     * Formats currency amounts for consistent display
     *
     * @param amount The amount to format
     * @return Formatted string
     */
    fun formatCurrency(amount: Double): String {
        return "R${String.format("%,.2f", amount)}"
    }
}