package com.example.tightbudget.utils

import android.widget.TextView
import com.example.tightbudget.models.ChallengeType

/**
 * Utility class for emoji icons in the TightBudget application.
 * This class provides convenient wrapper methods for accessing emoji icons
 * from the centralised IconProvider. It maintains backward compatibility
 * with existing code while delegating to the single source of truth.
 *
 * Note: This class now acts as a facade to IconProvider, which is the
 * centralised repository for all icon definitions. For new code, consider
 * using IconProvider directly.
 *
 * This class was generated by ChatGPT and was edited to match the application's needs.
 */
object EmojiUtils {

    // Standard text spacing between emoji and text
    private const val EMOJI_TEXT_SPACING = " "

    /**
     * Retrieves the emoji icon for a specific category.
     * This method delegates to IconProvider for the actual icon lookup,
     * ensuring all emoji definitions remain centralised.
     *
     * @param category The category name to find an emoji for
     * @return The emoji string for the category, with fallback to default emoji
     */
    fun getCategoryEmoji(category: String): String {
        return IconProvider.getCategoryIcon(category)
    }

    /**
     * Get a standard display text with emoji prefix
     * Ensures consistent spacing between emoji and text
     *
     * @param category The category name
     * @return Formatted string with emoji and text
     */
    fun getEmojiCategoryText(category: String): String {
        val emoji = getCategoryEmoji(category)
        return "$emoji$EMOJI_TEXT_SPACING$category"
    }

    /**
     * Set emoji with text in a TextView, with consistent spacing
     */
    fun setEmojiText(textView: TextView, emoji: String, text: String) {
        textView.text = "$emoji$EMOJI_TEXT_SPACING$text"
    }

    /**
     * Set emoji for a category in a TextView
     */
    fun setCategoryWithEmoji(textView: TextView, category: String) {
        setEmojiText(textView, getCategoryEmoji(category), category)
    }

    /**
     * Retrieves the emoji icon for an achievement badge.
     * This method delegates to IconProvider for centralised icon management.
     *
     * @param achievement The name of the achievement
     * @return The emoji string for the achievement
     */
    fun getAchievementEmoji(achievement: String): String {
        return IconProvider.getAchievementIcon(achievement)
    }

    /**
     * Retrieves the emoji icon for a challenge type.
     * This method delegates to IconProvider for centralised icon management.
     *
     * @param challengeType The type of challenge
     * @return The emoji string for the challenge type
     */
    fun getChallengeEmoji(challengeType: ChallengeType): String {
        return IconProvider.getChallengeIcon(challengeType)
    }

    /**
     * Retrieves the emoji icon for an action button.
     * This method delegates to IconProvider for centralised icon management.
     *
     * @param action The name of the action
     * @return The emoji string for the action
     */
    fun getActionEmoji(action: String): String {
        return IconProvider.getActionIcon(action)
    }
}